name: wireguard

services:
  backend:
    build: .
    # image: wireguard-docker:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE
    environment:
      - TZ=America/Sao_Paulo 
    volumes:
      - .:/code
      - ./logs:/code/logs
      - ./backup:/code/backup
      - ./database:/code/database
      - ./wg_configs:/etc/wireguard
    ports:
      - 8000:8000
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      # - net.core.rmem_max=2500000
      # - net.core.wmem_max=2500000
      # - net.ipv4.tcp_rmem="4096 87380 6291456"
      # - net.ipv4.tcp_wmem="4096 65536 6291456"

    restart: unless-stopped