name: wireguard

services:
  backend:
    build: .
    # image: wireguard-docker:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Sao_Paulo 
    volumes:
      - .:/code
      # - ./database:/code/database
      - ./wg_configs:/etc/wireguard 
    ports:
      - 8000:8000
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped