# Generated by Django 5.1.4 on 2024-12-26 16:24

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('listen_port', models.SmallIntegerField(default=51820)),
                ('private_key', models.CharField(editable=False, max_length=44)),
                ('public_key', models.CharField(editable=False, max_length=44)),
                ('endpoint', models.GenericIPAddressField(protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('persistent_keepalive', models.SmallIntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(editable=False, protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('private_key', models.CharField(editable=False, max_length=44)),
                ('public_key', models.CharField(editable=False, max_length=44)),
                ('preshared_key', models.CharField(default=app.models.generate_wg_psk, editable=False, max_length=44)),
                ('allowed_ips', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.server')),
            ],
        ),
    ]
