# Generated by Django 5.1.4 on 2024-12-27 19:10

import app.utils.wg_tools
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(default=app.utils.wg_tools.generate_private_key, editable=False, max_length=44)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('listen_port', models.SmallIntegerField(default=51820, unique=True)),
                ('endpoint', models.GenericIPAddressField(protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('persistent_keepalive', models.SmallIntegerField(default=25)),
                ('file', models.FileField(editable=False, null=True, upload_to='wg_configs')),
                ('file_md5', models.CharField(editable=False, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(default=app.utils.wg_tools.generate_private_key, editable=False, max_length=44)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(editable=False, protocol='ipv4', validators=[django.core.validators.validate_ipv4_address])),
                ('preshared_key', models.CharField(default=app.utils.wg_tools.generate_preshared_key, editable=False, max_length=44)),
                ('allowed_ips', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
