# Generated by Django 5.1.4 on 2024-12-28 01:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='file',
            field=models.FileField(editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(location='/etc/wireguard'), upload_to=''),
        ),
    ]
