# Generated by Django 5.1.4 on 2024-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_server_created_at_server_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='allowed_ips',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
