# Generated by Django 5.1.4 on 2024-12-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_server_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dst_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dst_host', to='app.peer'),
        ),
    ]
