# Generated by Django 5.1.4 on 2024-12-31 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_server_dst_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('last_handshake', models.DateTimeField()),
                ('tx', models.CharField(max_length=255)),
                ('rx', models.CharField(max_length=255)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peer')),
            ],
        ),
    ]
