# Generated by Django 5.1.4 on 2025-01-01 15:35

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_server_dst_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='dst_host',
        ),
        migrations.AlterField(
            model_name='peer',
            name='address',
            field=models.GenericIPAddressField(editable=False, protocol='ipv4', unique=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='server',
            name='file',
            field=models.FileField(editable=False, null=True, storage=app.models.WireguardStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PeerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('last_handshake', models.DateTimeField()),
                ('tx', models.CharField(max_length=255)),
                ('rx', models.CharField(max_length=255)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peer')),
            ],
        ),
    ]
