# Generated by Django 5.1.4 on 2025-01-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_server_dst_host_alter_peer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peer',
            options={'ordering': ['id'], 'verbose_name': 'Peer', 'verbose_name_plural': 'Peers'},
        ),
        migrations.AlterModelOptions(
            name='peerstatus',
            options={'ordering': ['id'], 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
    ]
