# Generated by Django 5.1.4 on 2025-01-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_peer_options_alter_server_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeerStatus',
        ),
    ]
