# Generated by Django 5.1.4 on 2025-01-02 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_peer_options_alter_peerstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
