# Generated by Django 5.1.4 on 2024-12-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_peer_address_alter_peer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='dst_host',
        ),
    ]
