# Generated by Django 5.1.4 on 2025-01-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_peerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerStatusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('preshared_key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('allowed_hosts', models.CharField(max_length=255)),
                ('last_handshake', models.DateTimeField()),
                ('tx', models.CharField(max_length=255)),
                ('rx', models.CharField(max_length=255)),
                ('keepaline', models.SmallIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.peer')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['id'],
            },
        ),
    ]
