# Generated by Django 5.1.4 on 2025-01-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_peerstatusunit_peerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerstatus',
            name='peer',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.peer'),
        ),
    ]
