# Generated by Django 5.1.4 on 2025-01-01 15:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_server_dst_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='file',
            field=models.FileField(editable=False, null=True, storage=app.models.WireguardStorage(), upload_to=''),
        ),
    ]
