# Generated by Django 5.1.4 on 2025-01-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_peerstatus_created_at_peerstatus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
