# Generated by Django 5.1.4 on 2025-01-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_peerstatus_peer'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='central',
            field=models.BooleanField(default=False),
        ),
    ]
