# Generated by Django 5.1.4 on 2025-01-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_peer_central'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='peer',
            constraint=models.UniqueConstraint(condition=models.Q(('central', True)), fields=('server',), name='unique_central_peer_per_server'),
        ),
    ]
